language: node_js
os: linux
node_js:
  - 12

cache: yarn
install:
  - yarn install
jobs:
  include:
    - stage: Build and test
      script:
        - yarn test
        - yarn build
    - stage: npm release
      script: yarn build
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: main
          # tags: true
    - stage: deploy gh-pages
      script: yarn run predeploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: ./example/build/
        on:
          branch: main

branches:
  only:
    - main
    # - /^v[0-9]+.*$/